(import (scheme base) (scheme write) (scheme file) (expand) (library-manager) (third-party pp)
	(scheme process-context)
	(util) (match)
	(passes)
	(srfi 1)
	(srfi 69)
	(format))
(define (get-double-as-u64 d)
  (let ((p (open-output-string)))
    (write-f64 d p)
    (let ((p (open-input-string (get-output-string p))))
      (read-u64 p))))
(include "bc.scm")
