(import (scheme base) (scheme write) (scheme file) (expand) (library-manager) (third-party pp)
	(scheme process-context)
	(util) (match)
	(passes)
	(srfi 1)
	(srfi 69)
	(srfi 151)
	(format)
	(prefix (flow sys) sys:))
(define (get-double-as-u64 x) (sys:FOREIGN_CALL "SCM_DOUBLE_AS_U64" x))
(include "bc.scm")
