(import (scheme base) (scheme write) (scheme file) (expand) (library-manager) (third-party pp)
	(scheme process-context)
	(util) (match)
	(passes)
	(srfi 1)
	(srfi 69)
	(format))
(define (get-double-as-u64 x) 0)
(define (bit-field-rotate a b c d) 0)
(define (bitwise-and a b ) 0)
(include "bc.scm")
