(define-library (passes)
    (import
     (except (scheme base) quasiquote)
     (scheme write)
     (scheme complex)
     (scheme cxr)
     (except (srfi 1) map!)
     (format)
     (srfi 69)
     (util)
     (third-party pp)
     (match))
  (export r7-pass)
  (include "qq.scm")
  (include "passes.scm"))
