(define-library (passes)
    (import
     (except (scheme base) quasiquote)
     (scheme write)
     (scheme complex)
     (scheme cxr)
     (scheme char)
     (except (srfi 1) map!)
     (format)
     (srfi 69)
     (util)
     (third-party pp)
     (match))
  (export r7-pass escapes-table global-labels const-label-label const-needs-label const-label?)
  (include "qq.scm")
  (include "passes.scm")
  (include "fix-letrec.scm"))
