name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: practical-scheme/setup-gauche@v5
      with:
        prebuilt-binary: true
    - name: setup
      run: |
        sudo apt-get install clang-19 libgmp-dev libutf8proc-dev
    - name: build
      run: make
    - name: test
      timeout-minutes: 3
      run: make test -j4 -k